modules/init-util.el

The real version are in a separate git repo, checked out under the local
dir. This function puts them into place to be picked up at exordium
startup.

Add util for linking exordium local config files

---

modules/init-look-and-feel.el

Match browser behavior.
Control wheel up and wheel down will zoom text in and out.

Bind text zoom to scrollwheel

---

modules/init-util.el

"elisp isn't a curly braced language"
"elisp isn't a curly braced language"
"elisp isn't a curly braced language"
...

Fix dangling paren

---

init.el

The `~/.emacs.d/local` directory doesn't exist by default, which causes the following error at startup:
```
Warning (initialization): An error occurred while loading `/Users/jbibollet/.emacs.d/init.el':
File error: Opening directory, no such file or directory, /Users/jbibollet/.emacs.d/local
```
This commit changes the `add-directory-tree-to-load-path` to check the directory exists before adding it.
**NOTE**:
- I don't know if this should silently ignore unknown directory in that generic function.. One thing I was considering was to pass an additional optional parameter to indicate whether the directory is optional or required. While I don't know how to do that, if this is a preferred way let me know and I can take it as an exercise to learn ELISP :)

add-directory-tree-to-load-path: Ensure the directory exists before adding it

---

.gitignore
init.el
modules/init-desktop.el
modules/init-prefs.el

Support saving the desktop state: open buffers, mini-buffer history, and point location in buffers. 
Off by default.

Support desktop mode

---

modules/init-dired.el

By default (on some platforms?) find-dired will exec ls on each
file. Xargs them and ls -ld as a group.

Find options for dired

---

modules/init-git.el

Starting with 1.4.0 magit will nag you about adding a line to your init
to stop warning you about an insane dataloss scenario. Magit autoreverts
unchanged buffers on git operations. This means if you save a file, then
do something like 'git reset --hard' the file could be changed out from
underneath you and autoreverted. This has been the behavior of the
unstable magit for a long time. The answer is "DONT DO THAT".
This turns off the warning.

Fix magit warning lossage

---

modules/init-bde-style.el

Repunctuating might change alignment, so call fill-paragraph to automatically reformat the paragraph to the 79 columns rule.

init-bde-style.el: Invoke fill-paragraph after bde-repunctuate

---

modules/init-git.el

Add a keybinding, "t", to the exordium git key map to toggle git
timemachine mode.

Key binding to toggle git timemachine

---

init-test.sh

Shell script to test exordium outside of ~/.emacs.d
Having the editor misconfigured while editing the init can be
inconvenient.

Shell script to test exordium

---

init.el
modules/init-cpp.el
modules/init-elisp.el
modules/init-javascript.el
modules/init-look-and-feel.el
modules/init-prefs.el
modules/init-prog-mode.el
modules/init-python.el
modules/init-ruby.el
modules/init-util.el

Programming modes inherit from prog-mode. Move the common c++, python, etc code into a single 
prog-mode module

Factor programming modes into prog-mode 

---

modules/init-util.el

Let fci-mode control whether or not truncate long lines when generating popup.
This lets buffers without fci-mode to use it's default value and wrap line when
it makes more sense (i.e., compile-mode).

Improve truncate-lines vs. fci-mode plus auto-complete

---

themes/color-theme-material.el

This fixes highlighting in Magit-mode. The change introduced with fix
138d2b513c4 for --daemon mode made hunks highlighting too much 'in your face'
(in other words: unreadable).

Fix magit hunk highlighting in material theme

---

modules/init-git.el

With a vanilla clone of exordium to `~/.emacs.d` , I found that the init phase hit issues (Emacs 24.4.1).
`emacs --debug-init` showed this to be a problem in `require(init-git)`:
`signal(error ("magit-auto-revert-mode is not currently registered as a minor mode"))`
The diff should diminish `magit-auto-revert-mode` only when registered. With the change, the init phase succeeded for a vanilla `.emacs.d` clone.
(I didn't have a case where "MRev" was shown in the modeline for comparison, but the method was http://stackoverflow.com/questions/10088168/how-to-check-whether-a-minor-mode-e-g-flymake-mode-is-on )

Only diminish "magit-auto-revert-mode" if registered

---

modules/init-bde-style.el

When using the BDE right align function, it leaves the cursor at the beginning of the right aligned text.
This change moves it to the end of the line, which I think suits more a typical workflow.

BDEStyle: leave cursor at end of line after right-align

---

modules/init-git.el

Magit 2.1 has different functions to display log for current branch and
current file. Let's use them when available.

Favour magit-2.1 functions over 1.4

---

modules/init-git.el

Magit 2 wants to run magit-blame, rather than magit-blame-mode.

Support magit-2 magit-blame

---

themes/color-theme-material.el

`far-background` is slightly darker than `background`, which I would prefer. `subtle` was too bright for me.

Change material theme's fringe color

---

modules/init-bde-style.el

BDE formatting doesn't work in narrowed buffers. As it turns out it's not exordium's fault, but indent-region's. Anyway, this PR temporarily widens the buffer before indenting.

Fix BDE indentation in narrowed buffer.

---

modules/init-cpp.el

when switching from header file to source file via `C-TAB`.  Useful when working with projects which use `.cc` extension for C++ source files.

Support 'cc' extension for C++ files

---

modules/init-rtags.el

Impelmentation has been changed recently in original Andersbakken/rtags.
It rendered pg/rtags-handle-results-buffer not working, since
rtags-not-indexed/connected-message-p was removed. Fortunately, the
new version of rtags-handle-results-buffer returns t when match
was found and custom implementation of it is not needed anymore

Retrofit rtags-find-symbol-at-point addendum

---

README.md
init.el
modules/init-helm-projectile.el
modules/init-helm.el
modules/init-ido.el
modules/init-prefs.el

Add an option to use Helm as a replacement for IDO. By default it
is off. However when exordium-helm-everywhere is true Helm is used
by default.
Optionally allow for fuzzy matching when selection is narrowed
(default true).
Add a few keybindings to use Silver Searcher (Ag) with helm for
quick code scanning.

Use Helm as a default completion and selector

---

modules/init-rtags-helm.el

When `exordium-helm-everyhere` is set to true turn on
helm functions from rtags as well as Exordium ones.

Use helm also for rtags when requested everywhere

---

modules/init-powerline.el

Projectile and Tramp don't get along if the directory is remote. Change
the modeline setting in powerline to not call projectile-project-name.

Fix modeline for Projectile/Tramp

---

modules/init-cpp.el

Some projects keep their test files in test sub-directory.
The latter can be either on the source level or on the
sub-module level. Let the `cpp-switch-h-cpp` use the
test when searching for test file.

Look for tests in test subdir to cpp-switch-h-cpp

---

modules/init-rtags-helm.el

rtags-helm has it's own module since [Oct/17 commit to rtags](https://github.com/Andersbakken/rtags/commit/89af223e64d9d918517c9ae7b29e9550389105dd#diff-7102a2397f5f68a580cf204addc04da9).

Make sure rtags-helm is loaded

---

README.md
doc/code-organization.md
init.el
modules/init-company.el
modules/init-prefs.el
modules/init-rtags.el
modules/init-util.el

This enables company-mode (globally) as an alternative to
auto-complete. While I haven't tested it extensively yet it
integrates with RTags pretty nicely and seems to work out of the box.
You can change which mode you want to use by setting
exordium-complete-mode to either :auto-complete or :company (or nil to
don't choose either).

Add company-mode as an alternative to auto-complete

---

modules/init-rtags.el

The `company-backends` is nil otherwise and that causes
`memeber` to produce diagnostics.

Only delete rtags-company when in company mode

---

modules/init-cpp.el

This adds `u.t.cpp` and `i.t.cpp` as a possible extensions for test files.
Moreover, it is more diligent when searching for possible file locations:
* test files are searched both in current and in test sub-directories
* headers and cpp/cc files are searched in current, in parent, and
in parent/group directories

Improve h to cpp to t.cpp switching

---

modules/init-company.el

'company' is a bit too long to my taste. Let's use 'CA' which is
not only shorter, not only respects Complete Any but is an anagram
of 'AC' used by the competition a.k.a auto-complete.

Clean up line mode for company

---

modules/init-bde-style.el

This is useful i.e., for yasnippets.

Recognise longer suffixes of test drivers

---

modules/init-util.el

C-x C-/ as a reverse of C-x C-\ is both more predictable and easier to type.

Easier to type binding for goto-last-change-reverse (C-x C-/)

---

README.md
modules/init-iwyu.el

I caught myself hitting `g` in the IWYU result buffer. But it was spawning full compilation. Not exactly what I was expecting. Now it's more intuitive - at least to me.

Use `g` to iwyu reocmpile

---

modules/init-bde-style.el

When the component name starts with `s_` we need to search for the following `_` to get its name.

Support `bde-component-name`s starting with s_

---

modules/init-bde-style.el
modules/init-bde-style.t.el

It should enable support for modern c++, however there are some caveats:
- full c++11 syntax is not supported (i.e. no support for `noexcept' operator,
nor for trailing return types),
- it is probably to permissive (errors should be caught by a compiler anyway),
- it requires certain order of key words,
- it doesn't support `final' keyword.
Yet it should be more helpful with BDE style member function comments.

Smarten the member function detection.

---

modules/init-linum.el

It's a compilation mode after all and line numbers there are
excessive.

Suppress `iwyu-mode` in `nlinum`

---

modules/init-iwyu.el

I think `cc` is used more often than `ccc` for c++ files ;).

Fix iwyu-mode cc extension

---

modules/init-rtags.el

exordium-rtags-rdm-args was not handled correctly for multiple arguments.  This also simplified the code slightly.

Fix exordium-rtags-rdm-args handling

---

modules/init-markdown.el

electric-pair is pretty addictive when (ab)used on blocks of text.
And selecting a command in markdown, then hitting a backtick key
only to realise the next thing to do is to hit `C-z` wasn't a good
experience to me.

Make backtick an electric pair in markdown mode

---

modules/init-bde-style.el
modules/init-bde-style.t.el

It requires the declaration to be close to complete, but allows to have
some templates crazy magic to be nicely aligned. It also allows for unlimited
stars and accepts more variable names (even thought they are not BDE convention).

More robust align-fundecl

---

modules/init-bde-style.el
modules/init-bde-style.t.el

Two improvements to `bde-align-fundecl`:
- limit searching for open and close params to 4000 characters
- align default values

Limit range and align default values in `bde-align-fundecl`

---

modules/init-cpp.el

I think I didn't know about `diminish` when I added the
`modern-c++-font-lock-mode`. Yet when we use `legacy` mode it doesn't taint
the mode line. On top of that `mc++fl` doesn't even give any extra
functionality there.

Diminish modern-c++-font-lock-mode

---

modules/init-helm.el
modules/init-ido.el

Most noticeable, at least for me, was `ido` under `C-x C-w` and `C-x i`.
Now `helm` works under `magit` as well, just try `b c`.

Truly use helm everywhere

---

modules/init-linum.el
modules/init-prefs.el

I admit the hack with defining own custom global mode is not something I'm particularly proud of. I wish there was some better customisation point. However, for now it seems to do the job and `nlinum` (despite its quirks) gives me observable speed difference  over `linum`.
- use custom `exordium-global-nlinum-mode` for common inhibitions
- add inhibition for buffers that name starts with `*`
- add inhibition for large buffers
- remove fix for font size in nlinum when zooming

 Refactor line numbers

---

modules/init-bde-style.el
modules/init-bde-style.t.el

Not for all possible cases (see the `TODO`), but should be good
for the ones met in the wild.

Fix `bde-align-funcdecl` for c-tor with initizlizer list

---

modules/init-git-visit-diffs.el

Display the position of the hunk being viewed, and the number of remaining hunks.

init-git-visit-diffs: show position in diff list

---

.gitignore
modules/init-org.el

The first one is to accommodate new files while the latter udpates `sh` to `shell` for org-9.1.9

Update gitignore and init-org

---

doc/snippets.md
modules/init-linum.el
modules/init-org.el
modules/init-prefs.el
snippets/c++-mode/bael_warn
snippets/c++-mode/ball_category
snippets/c++-mode/ball_debug
snippets/c++-mode/ball_error
snippets/c++-mode/ball_info
snippets/c++-mode/ball_trace
snippets/c++-mode/ball_warn
snippets/c++-mode/implementation
snippets/c++-mode/locked
snippets/c++-mode/now
snippets/c++-mode/sleep

BDE has evolved a bit and deprecated some of them. I've chosen the monotonic clock as it seemed more relevant to the time measurements in the backend.

Modernize snippets

---

modules/init-git.el
modules/init-prefs.el

Added this as an opt-out as the git-gutter was responsible for
~2/3 of the time emacs was 'tramping' for remote files in git
repository.

Don't use git gutter for remote files

---

themes/color-theme-github-modern.el
themes/github-modern-theme.el

Theme data copied from
https://github.com/philiparvidsson/GitHub-Modern-Theme-for-Emacs
Added exordium powerline faces, and large fonts for org mode.
A light theme, useful for exporting colorized code.

Add github-modern theme

---

README.md
modules/init-git.el

I find these keys to be easier to reach on MacBook keyboard.

Add ^c g n and ^c g p for git gutter hunks navigation

---

modules/init-prefs.el
modules/init-yasnippet.el

Use preference, defaulted to user-full-name (user-login-name) rather than
"Philippe Grenet (pgrenet)".

Add a preference for yasnippet author

---

.gitignore
init.el

Don't append to after-init.el, instead save to a distinct file, and git ignore
that file.
I have my after in git, so letting emacs write to it is annoying.

Move customize to its own file

---

README.md
modules/init-git.el

In my mind this is more dwim. And nice when digging through repo history.

Use `magit-dired-log` when in `dired-mode`

---

README.md
modules/init-git.el

I find myself using it more and more in recent days, especially when the
default in my `magit-clone-name-alist` lets me to use only `organisation/repo`
to specify the source of a clone.

Add magit-clone to the git keymap

---

README.md
modules/init-git.el
modules/init-prefs.el

In the beginning I didn't like it, but now I found that lack of full-screen
after `M-g` in `helm-projectile-switch-project` causes a dissonance. Decided to
do more robust checks.
Apologies for the ugly advice names, but didn't want to repeat the same code
more times, nor I know how to do macros inside a macros that want symbols
etc... my `elisp` still needs more refinements...

Make more magit functions to go full screen

---

modules/init-org.el

org-bullets is deprecated, and latest version in MELPA is actually
empty. Probably a bug, but superstar is the maintained successor, and a drop-in
replacement.

Switch to org-superstar

---

modules/init-org.el

MELPA version of org-bullets is broken. Switch to the maintained successor,
org-superstar, a drop in replacement for org-bullets.

Switch to org-superstar, the maintained version of bullets

---

modules/init-bde-style.el
modules/init-bde-style.t.el
modules/init-cpp.el
modules/init-flb-mode.el
modules/init-iwyu.el
modules/init-lib.el
modules/init-look-and-feel.el
modules/init-rtags-cdb.el
modules/init-rtags.el
modules/init-smooth-scroll.el

Emacs 27 is deprecating cl. Switch to using cl-lib instead.

Change to cl-lib to handle deprecation of cl in 27

---

modules/init-git.el

After doing `magit-clone` (<kbd>C-c g c</kbd>) `magit-status` buffer is
automatically open. This however doesn't add it to `projectile`'s known
projects. It stays this way until a file from a fresh clone is open. When in
this state it's not possible to quickly go to the project with
<kbd>C-c H</kbd> (i.e., `helm-projectile`).
This commit adds advice to automatically add a project to a list of
`projectile`'s know projects after `magit-clone`.

Add project to projectile after magit-clone

---

themes/color-theme-tomorrow.el

Org's level one now looks like this:

Tune Tomorrow theme for Org mode

---

modules/init-look-and-feel.el
modules/init-org.el
modules/init-prefs.el
modules/init-prog-mode.el
modules/init-themes.el
modules/init-util.el
themes/color-theme-atom-one.el
themes/color-theme-github-modern.el
themes/color-theme-material.el
themes/color-theme-monokai.el
themes/color-theme-solarized.el
themes/color-theme-tomorrow.el
themes/color-theme-zenburn.el

This replaces the `fill-column-indicator` a.k.a `fci-mode` with the native `display-fill-column-indicator-mode`. The old mode is still used when `emacs-version` is below 27 (i.e., the new native mode is not available).
The new mode look and fill replicates the old one with the following modifications:
- It's now possible to define how the dashes should be displayed via `exordium-fci-use-dashes` value and fine tune it with `exordium-fci-dashes-alist`. Old settings are still supported.
- The temporary buffer for org source code blocks is not inhibiting the new indicator. While that behaviour is there for the last 5 years (introduced by @steve-downey in: fe8be638679f5edfc2cc3e834b02e071e4d78219), it lacks motivation and  I think that lack of indicator there is quite surprising. Especially …

Use native display-fill-column-indicator on Emacs 27 and above

---

modules/init-util.el

If the package is deferred the `:config` is not always executed on startup. When that happens there's no indicator in buffers that should have it on automatically. Use `:demand` to override implicit deferred loading introduced by `:bind` and force the load on startup.

Demand using display-fill-column-indicator

---

themes/color-theme-atom-one.el
themes/color-theme-github-modern.el
themes/color-theme-material.el
themes/color-theme-monokai.el
themes/color-theme-solarized.el
themes/color-theme-tomorrow.el
themes/color-theme-zenburn.el

When the text with `:slant italic` is long enough to touch the column
indicator (but not cross it), the indicator inherits the slant from text. I'm
not finding this very pleasing. Fixing it to use `:slant normal`.
Without fix:
With fix:

Use :slant normal for display-fill-column-indicator

---

modules/init-git.el

The `:diminish` by default use name of the package with added `-mode` to
automatically detect what to remove. However, in a case of `git-gutter-fringe`
we use `git-gutter-mode` and this was not working as intended, leaving
`GitGutter` in the status line. Fix this by explicitly providing minor mode symbol.

Diminish GitGutter from status line

---

README.md
modules/init-git.el

When solving merge conflicts with `ediff` I found myself more than once in a
need of having changes from both conflicting branches to be in final
merge. Sometimes they need refining, but usually parts of the conflicting
region were useful as is. IDK how to achieve that in a standard `ediff` without
selecting one change and then manually copying the other one.
This commit adds two keybindings to Ediff Control Panel: <kbd>A</kbd> and
<kbd>B</kbd>. They copy changes from both conflicting regions to the `C`
buffer. Two keys to allow for specifying order of yanks in a `C`.

Add option to copy both buffer regions in ediff

---

doc/code-organization.md

Replace links in docs with internal to repo links so that it will stay within
the repository.

Replace https links with internal repo links

---

modules/init-util.el
themes/color-theme-solarized.el

This update is focused on the `light` flavour. I found the original one to be a little bit too nettling to my eyes. And sometimes the text became plainly unreadable (i.e., `region`).
I've been using these fixes for a while now (if you take look at the commits history) and have not been finding much need to tweak it recently. Hence the PR.
As a last ditch, I've added tab-bar theme, that I've been using for a few days now.
I've also eye balled `dark` version and it seems to behave pretty consistently with the `light` version.

Update solarized theme

---

themes/color-theme-tomorrow.el

Just a small change in the Tomorrow's theme for tables. It looks like this:

Add new face for markdown tables

---

modules/init-cpp.el
modules/init-iwyu.el

Apparently `remove-if` is only an alias for `cl-remove-if`. Yet it's been giving me a warning in `init-cpp.el`. I scanned whole repo and use `cl-remove-if` consistently across it.

Use cl-remove-if

---

README.md
modules/init-helm-projectile.el
modules/init-helm.el

I noticed the `C-c p` has stopped working, so decided to give the setup a small refresh.
The `helm-projectile-on` is doing substitutions much more diligently, and I guess this is what is expected from `exordium-helm-everywhere`.
Since I've never used the `helm-ag-project-root` as the `C-S-a` was doing the same job I decided to give the binding to `helm-projectile-rg`. The `ripgrep` seems to be better in certain places than the Silver Searcher, i.e., it can do multi line searches.

Refresh projectile set up and add ripgrep

---

modules/init-helm.el

Quite often I find myself wanting to type something from the _last_ window (where a `point` was at the time of invoking helm function), but the contents of the window are clobbered.
The value of  `other` works very close to the original value of `below`. The difference is when `point` is in a _last_ window. With the default value, when `helm-buffer` is to be shown it is done in the _last_ window.
To describe with a screenshot, the window `d` is the _last_ window:
- When the value is `'below` and a helm command is invoked from window -> the `helm-buffer` ends up in window:
- `a` -> `s`
- `s` -> `d`
- `d` -> `d`
- When the value is `'other` and a helm command is invoked from window -> the `helm-buffer` ends up in window:
- `a` -> `s`
- `s` -> `d`
- `d` -> `a`
I've also checked the …

Use `'other` for a `helm-split-window-default-side`

---

modules/init-cpp.el

The issue is described in https://github.com/victorhge/iedit/issues/114.
For now I got that the `electric-pair-inhibit-if-helps-balance` [has been updated in Emacs 27](https://github.com/emacs-mirror/emacs/commit/e66d5a1) and that causes issue to appear.
I'd love to create a proper fix, however, I haven't time yet to devise a one. The sheer size of `electric-pair` and `iedit` packages (especially their state and workarounds for different things in them) is just too much for me to consume at the moment. Perhaps the real solution would be to implement the `FIXME` added in the aforementioned commit?
Yet the issue happens often enough, that I wanted to do something about it. I decided to sacrifice the _some markers position_ and get back to the _old_ way of doing doing things when in …

Workaround `electric-pair` and `iedit` interference issue

---

modules/init-cpp.el

This reverts commit 9a17a437c800c825401010cc7bdb9ef671534b83.
No longer needed - `iedit` [has been updated](https://github.com/victorhge/iedit/commit/d9ebfb8).

Revert "Workaround `electric-pair` and `iedit` interference issue"

---

README.md
modules/init-helm-projectile.el
modules/init-helm.el
modules/init-ido.el
modules/init-rtags.el

Move most of `helm` related stuff into `init-helm` and only left `projectile`, `helm-projectile`, and `treemacs` in `helm-projectile`. It changes semantics a bit, since now `helm-swoop`, `helm-ag`, and `helm-rg` will be always loaded, albeit bindings will point to different functions depending on `exordium-helm-projectile`.
It also changes how the completion works. Recent `helm` seem to advise to use
the `completion-styles` now to configure this globally. So I removed all
variables that were pointing to some kind of  /fuzzy/ completion mode, and use
`flex` instead.
I've also changed bindings in `helm-swoop-edit-mode` to follow these from
`helm-ag` - after all `C-c C-c` to accept and `C-c C-k` to cancel are the same
as in `magit`.
The `:diminish` has to be done twice as the second load …

Refactor init-helm.el

---

modules/init-linum.el
modules/init-prefs.el

Also add `magit-mode` to the list. I didn't find usefulness of line numbers in `magit` buffers like status, log, commit preview, etc. On the other hand it can make emacs even slower when opening a commit with large diff inside. Happy to remove if it is useful by default.

Don't enable line numbers if mode is inherited from exordium-inhibit-line-numbers-modes

---

README.md
init.el
modules/init-forge.el
modules/init-git.el

Move forge into it's own `init-forge.el` file and add some extra support:
- `markdown-preview` function - that requires the `markdown-preview` to work in regular `markdown-mode` buffers.
- draft Pull Request submission and marking as Ready for Review; unfortunately I haven't been able to add support for displaying status of these; probably something in a `forge-topic-mode` and in a `magit-status-mode` but that would likely require to update `forge-db`, so will likely have to come from upstream.
I've chosen to overload `C-c C-d` for draft Pull Request submission and marking as ready for review. Hopefully you'll like this.
To validate this: I'm previewing text of this PR, then submitting it as a draft followed by marking as ready for review. What a nice workflow 😎.
Please note that this PR …

Add init-forge with markdown-preview and draft PR support

---

themes/color-theme-zenburn.el

:inherit can't be followed by :weight. Change to inherit from
exordium-variable-pitch.
----
#

Fix broken markdown mode face in zenburn theme

---

modules/init-prog-mode.el

Make sure the flyspell package is loaded and configured if using
flyspell-prog-mode as a prog-mode-hook.
----
#

Make sure flyspell is loaded when adding the prog-mode-hook

---

README.md
init.el
modules/init-elisp.el
modules/init-helm.el
modules/init-help.el
modules/init-lib.el
modules/init-prefs.el

Add `helpful` and `which-key` as well as add `C-c C-o` keybinding in `help-mode`.
I've been using `helpful` for over 2 years now.  I think they are both really useful, hence I took a liberty and enabled that by default.
Over the course of 2 years I've extended the setup a bit (like hooking up into helm, but not fully yet, due to a [lack of support in `helm-descbinds`](https://github.com/emacs-helm/helm-descbinds/pull/30).
I really got to liking `C-c C-o` when working with `magit` and `forge` and I was missing this a lot when reading help for a function or a variable or a synopsis of some package (in `package-list-packages`).
Perhaps a window management could be improved so it doesn't clobber all available windows when digging deeper and deeper in a help links, but I leave it out for a …

Add help extensions

---

modules/init-rtags-helm.el
modules/init-rtags.el

- Add missing packages, so it compiles without errors.
- Use `:bind` so the binding is defferred to a moment the map is defines.
- Add extra binding to `helm-command-map` (`C-x c f`):
- It overrides `helm-multi-files` - I've never used that, but if you do, I'm happy to use a different binding. Suggestions?
- Update `flycheck-rtags` to use regular function for a hook, so it has no problems when running tests in `init-bde-style.t.el`.

Refactor helm-flycheck

---

modules/init-elisp.el

This is to only register hook after the `use-package` to avoid issues first
start when packages are downloaded, like here: https://github.com/emacs-exordium/exordium/runs/1673475767

Refactor init-lisp

---

README.md
modules/init-git.el
modules/init-helm-projectile.el

I found myself to search in a different project than the currently selected. That means that I usually did:
- `C-S-h`
- find the project
- either hit `RET` on it and select a file in the project, then hit `C-S-a` and start searching
- or hit `M-g`, hit `C-S-a`, hit `M-backspace`, start searching
This change lets to trigger a search (with an `ag` or a `rg`) directly from a `helm-projectile-switch-to-project`. It's enough to set the point on a project you wish to search, and hit `C-S-a` or `C-S-r` and start typing your query. So now I can
- `C-S-h`
- find the project
- hit `C-S-a` and start searching
I've also addressed the insertion of a symbol at point when initiating an `ag` search or a `rg` search from `magit-status` buffers. I found that I seldom have a need to use anything from a …

Allow to start ag/rg directly from helm-projectile

---

README.md
modules/init-git.el
modules/init-prefs.el

When I resolve merge conflicts I'd like to use keybindings to pick correct hunks. One option is using `ediff`, another is to rely on a more lightweight SMerge. The latter is loaded by default when hitting `RET` on a file that is marked as  `unmerged` in a Magit status buffer. However, I don't do merge often enough, that merge related keybindings had a chance to engrave in my memory. I'd like to see available keybindings in front of my eyes.
Add a `transient` that is showing bindings for commands from `semrge-mode`. I took an idea from some forum post a few years back (can't find a reference though). Have also seen similar solution being implemented in [DOOM](https://github.com/hlissner/doom-emacs/blob/0769b47/modules/emacs/vc/autoload/hydra.el) yet it uses `hydra-mode` and VI-style …

Add a transient dispatch for SMerge mode

---

modules/init-git.el

So `transient` functions are defined. I didn't notice it earlier, as it was in my `after-init` so `transient` always had a chance to be installed.

Wrap exordium-smerge-transient in use-package

---

modules/init-cpp.el

The fix for `cmake-mode` has been merged. Let's see if this passes CI.
This reverts commit f7f003b0aa228d6ffc96229d106288d494c89cdb.

Revert "Disable cmake-mode on emacs-26"

---

modules/init-org.el

The `sh` was pre org-9.0. However, the lowest supported version of emacs (26.1) is shipped with org-9.1.9, so the check is redundant. To add to that org-9.4.4 in `gnu` package does not define a string version, causing the check to yield a failure.

Only use shell in org-babel

---

.github/workflows/tests.yml

This has started giving `invalid-syntax-error`'s. This happened on `ubuntu-latest` for 27.1, 26.3 and a few other versions (other pipelines were aborted). See [here](https://github.com/pkryger/exordium/runs/1717059084). I've tried to disable `cider` but that just have shifted error elsewhere, see [here](https://github.com/pkryger/exordium/actions/runs/491777870).
While I would like to see we do compile on CI as it pulls more packages than the regular start and we could catch more errors early (i.e., like the [one]() in  `cmake-mode`), but I haven't figured out yet how to debug that to a point where I would be able to propose a fix. Any pointers welcome.
-----
A stack from the [original](https://github.com/pkryger/exordium/runs/1717059084) failure for a reference (`ubuntu-latest, 27.1`) …

Disable compilation on CI

---

.ci/unit-tests.sh
.github/workflows/tests.yml
modules/init-forge.el
modules/init-forge.t.el

It's been inspired by and named after a `projectile-cleanup-known-projects`. But unlike it's predecessor it is executing in a separate process to not to block UI. Because of that I had to made a few trade-offs that I tried to describe in comments in code.
The feature has been motivated by my recent realisation that I have done PRs well over 150 different repositories for last year. That made searching for a project a bit cumbersome, even with a help of `helm-projectile`. Since I was not expecting to do any further PRs to around a 100 of these repositories so I deleted them, then run `projectile-cleanup-known-projects`. However, there's no counterpart for `forge` database for that. The list from `forge-list-repositories` was long and I didn't had a method to clean it nicely like I've done …

Add forge cleanup

---

.ci/unit-tests.sh
modules/init-util.el
modules/init-util.t.el

I've found myself programming in a few different languages that have multiple string formats, i.e., `?\'` and `?\"` delimeted (single and triple). What's more different projects use different conventions and are sometimes pretty picky on how the string is quoted. In some places it makes a semantic difference as well - looking at you Groovy's `GString`. Long story short,  I've found myself flipping these quotes manually more often than I'd like to. And that's a bit tedious.
I've Googled a bit for a solution, but haven't found anything that would work to my satisfaction. Hence, I came up with a one that handles most of cases that I've encountered (and a few more that I came up while writing). That is the `exordium-flip-string-quotes` function.
The function is capable of flipping quotes in a …

Add exordium-flip-string-quotes

---

modules/init-help.el

This lets to dig deeper, using helpful, when browsing code in `helpful-mode`.  I think I like it better in many situations than `xref-find-definitions`. This looks like an `elisp` buffer after all.

Bind C-c C-d in helpful-mode

---

.ci/compilation.sh
.ci/unit-test-cl.sh
.ci/unit-tests.sh
.github/workflows/tests.yml
modules/init-bde-style.el
modules/init-cpp.el
modules/init-flb-mode.el
modules/init-rtags-cdb.el
modules/init-rtags-cmake.el
modules/init-rtags.el
modules/init-util-cl.t.el
modules/init-util.el

More and more packages stop using `cl.el`. The latter has a nice loop that defines aliases to new `cl-lib.el` names (the ones that start with `cl-` prefix). This causes surprises, when `cl.el` is not included anymore by one of the underlaying packages.
I've started by fixing known candidates like `case`, but then thought about more systematic approach. So I've taken the loop from `cl.el` and applied it to `elisp-refs` find functions and manually fixed all occurrences (my lisp-fu ain't good enough to do that automatically yet). But later I thought that it's quite easy to degenerate the code by using some of the non `cl-` prefixed aliases, so I expanded that idea to have:
- an interactive function `exordium-refs-cl-aliases` for humans to find mistakes,
- an automatic test that is running …

Don't use functions from an obsolete cl.el

---

modules/init-elisp.el
themes/color-theme-tomorrow.el

I changed the markdown faces to be more readable. This is inline with common other themes for [other editors](https://kortina.nyc/essays/suping-up-vs-code-as-a-markdown-notebook/). Looks like this:

Add markdown changes for Tomorrow theme

---

modules/init-git.el

This prevents the `register-alist` to overgrow. The `register-alist` is one of variables being saved by `desktop-save-mode`. I'd rather the Exordium feature not to interfere with the latter than to remove `register-alist` from `desktop-globals-to-save`.

Remove magit-fullscreen- from register-alist after use

---

modules/init-git.el

I've run into a few issues when using most recent implementation of `exordium-magit-fullscreen`.
When debugging it turned out that magit calls a few advised functions from each other. That was resulting in an intermittent windows configuration to be stored in a register.
A short dive into `window-configuration-to-register` showed that storing window configuration is actually a very simple operation. That allowed to do a simple check for a variable existence in a stack (defined in a `let` form), to only capture the very first window configuration.
In addition I've decided to re-purpose the extra level of indirection - i.e., the buffer local variable used to strore register name. Now it holds desired windows configuration that is applied in `magit-quit-session`.
Changes above allow for a …

Don't use register for exordium-magit-fullscreen

---

themes/color-theme-tomorrow.el

Small change to the tomorrow theme for org mode, to make the "done" items (here `STOP` and `DONE`) be grayed out, so the stuff that is not done is more visible.

add org-headline-mode

---

modules/init-git.el
modules/init-org.el
modules/init-prefs.el
themes/color-theme-atom-one.el
themes/color-theme-monokai.el
themes/color-theme-solarized.el
themes/color-theme-tomorrow.el
themes/color-theme-zenburn.el

This adds a few visual changes to the Tomorrow theme for Org-Mode and Markdown: essentially the title and headers are more visible. It also adds support for various styles of git-gutter-fringe in preferences. The `:default` style does not change anything, while the `:flat` style shows flat git markers similarly to Doom-Emacs or modern editors like VS-Code. For example:

Add visual changes to org-mode, markdown and git gutter fringe

---

.ci/first-start.sh
.github/workflows/tests.yml
.gitignore
modules/init-util.el

There are a few updates here, but I think they can go in a single PR:
- After upgrading to 28.1.90, Emacs decided to create a completely new `elpa-28.1.90` directory and reinstall all packages. I've extended `.gitignore` to account for that.
- Update to CI to include Emacs 28.1.
- Update CI so it will pass tests with my taps.
- Update CI to make macOS more likely to pass. Apparently there was a race condition when melpa packages are installed. It, however, cannot be resolved in a batch mode - the `ask-user-about-lock` signals error. Documentation for the latter suggest it's intended for the user to override it. I decided to take a strategy of waiting for 5s then grabbing the _lock_ anyway (and keeping fingers crossed that the other thread has already released the _lock_). N.B. from the …

Update CI for emacs 28

---

modules/init-docker.el

It's been introduced recently with #197, but it clashes with `duplicate-line-or-region`. Let's go back to original behaviour and use something similar, albeit slightly more difficult to type.

Use `C-c D` for docker

---

modules/init-org.el
themes/color-theme-github-modern.el
themes/color-theme-material.el
themes/color-theme-monokai.el
themes/color-theme-solarized.el
themes/color-theme-tomorrow.el
themes/color-theme-zenburn.el

This is a set of rather opinionated tunes and refactoring I've done to `org-mode`. This set contains multiple fixes, and I guess the best way to review it would be to commit by commit. In a broader stroke these include:
- Updates to solarized theme. I've not been using it for a while (for the favour of `modus-themes`), but this encapsulates my opinionated fixes to it. These were done in light version (which was my primary theme), so the dark one may be not up to date
- todo keywords: TODO, WORK, WAIT, DONE. I've chosen them such that they are nicely aligned with a proportional font. I've also added two custom faces for them, such that highlighting stays consistent.
- Refactor `org-mode` setup into relevant `use-package`s.
- A few fixes and improvements: sql in babel, more blocks …

Fine tune org-mode

---

.ci/unit-test-cl.sh
modules/init-forge.el

IIUC, `forge` requires a `sqlite3` backend. It's up to user to ensure it's there: built in (default for Emacs 29), or extra package if not.  See the in-code comments for more details.
Caveats:
- The `debug-on-error` has to be `nil` when loading `/init.el`, since our current CI doesn't come with `sqlite3` library (https://github.com/purcell/nix-emacs-ci/issues/160). I moved it for `unit-test-cl.sh` since it's required for the tests to fail when deprecated functions are used.
- Not sure how to communicate this to users, that they need to come up with a properly configured OS (i.e, with `libsqlite3` available) or Emacs 29.

Add forge dependency: sqlite3

---

modules/init-docker.el

Facility is now built into emacs 29.

Avoid docker-tramp when emacs >= 29

---

.github/workflows/tests.yml
modules/init-treesit.el

Scanned what `-ts-mode` were available in my Emacs-29 and added forwarding hooks for them.
Also enable CI for Emacs-29, as I presume the snapshot will be drifting away from there.

Enable more treesit modes in Emacs 29 and add Emacs 29 to CI

---

modules/init-treesit.el

I think requiring `treesit` and `treesit-auto` configuration to be evaluated  after `lsp-mode` is excessive. I'm not using the latter (`eglot` fan here), and because of neither of these configurations loads for me.
I also updated a `SPEC` form in `when-let` - i.e., only the `(VALUEFORM)` can be used without creating a binding.

Don't depend on lsp-mode for treesit

---

init.el

Had some issues with CI and forge when developing my own tap. So far debugged it to:
- Some packages (i.e., `magit`, `forge`) require `seq-2.24`.
- Emacs-29 is delivered with `seq-2.23`.
- Other packages (i.e., `compat`) require `seq-2.23`.
- When only `magit` is installed it requires `compat` which requires `seq-2.23` -> `seq` is not upgraded
- When only `forge` is installed is requires `magit` and `compat`; the latter requires `seq-2.23` -> `seq` is not upgraded
- When `magit` is installed followed by installation of forge `seq` is upgraded to `seq-2.24` -> this fails
I think there are at least 2 issues here:
- just `(package-install 'forge)` will not install required `seq-2.24` - if I got it right, this is issue with dependency resolution in `package`
- installation of `seq-2.24` fails …

Workaround issues with seq-2.24 installation

---

init.el
modules/init-cpp.el
modules/init-org.el
modules/init-prefs.el

Discovered while factoring out some code from a taps' after-init.el that I couldn't (require 'org2blog-init) because it couldn't be found. So this adds taps to load the load path.

Add the taps directories to load path

---

README.md
init.el

Make initial calls to package refresh contents only when these may be
necessary, for example after Exodrium upgrade or on Exordium's first-start, or
when ELPA directory has been removed.
Add command line arguments to allow user to force and inhibit package refresh
contents.
Fixes #227

More controlable package-refresh-contents

---

.ci/unit-tests.sh
README.md
modules/init-help.el
modules/init-highlight.el
modules/init-highlight.t.el
modules/init-prefs.el

I have struggled to tune `hightlight-symbol` for the last few weeks. I've
encountered numerous issues, like automatically highlighted symbol not being
visible in current line (with `font-lock`'s background) due to conflict with
`hl-line` mode's overlay, `jit-lock` mode not flushing (required an advice
workaround), automatic highlighting clobbering `helpful-mode`
fontification (haven't got to the bottom of it), conflict in `highlihgt-symbol`
defun (both `highlight` and `highlight-symbol` defined it). It also seem to be
unmaintained - last version on MELPA is from 2016.
I've chosen to switch to `symbol-overlay`. Amongst others it defines its own
symbol highlighting. So I decided to use that instead of Exordium's custom one
that required `highlight`.
The last but not least `symbol-overlay` …

Switch to symbol-overlay from highlight-symbol and highlight combo

---

init.el
modules/init-vc-checkout.el
modules/init-vc-checkout.t.el

This is meant to allow users to have certain packages installed from their
custom checkouts, without a need for careful blocking installation of certain
packages in Exordium (for example with custom options) or going through
uninstall ELPA package/install checkout each time Exordium rebuilds
`package-user-dir` contents.
Please see Commentary in `exordium-vc-checkout.el` for more information.

feat(package): Allow overriding packages sources with exordium-vc-checkout

---

README.md
modules/init-git.el

A little bit of shameless plug (my first package on MELPA 😎), but I think it's
really usefull. If you haven't tired `difftastic` yet, I strongly
recommend. Even if as a standalone tool on a terminal.
I have been waiting for the `vc-checkout` (#235) to allow me to seamlessly use
my checked out development version while in Exordium.
Just to give a taste what's the difference is, please check out the screenshot below with exactly the same change being viewed with `difftastic` in top and regular diff (ignoring whitespace changes) in bottom.

feat(diff): Add difftastic - a front end to structural diffs

---

.ci/batch-flycheck.el
README.md
modules/init-git.el
modules/init-help.el
modules/init-look-and-feel.el
modules/init-window-manager.el

This PR aims at improving experience when searching for help in Emacs. Just a
short enumeration of changes:
- add `casual` - I found it super useful for modes I use only casually (see
what I did there 🤪),
- update `helpful` buffers to stick to the same window,
- update completing-read experience when using `helpful` - display extra
details and allow to peek at docstring (like in `helm-M-x`),
- update `help` buffers to use clean buttons (i.e., remove ticks around things
that are clickable and should be displayed using appropriate face), and stick
to the same window when clicking around,
- update `smerge` mode to recenter around the first unmerged,
- update docs to reflect the above,
- update CI as snapshot Emacs now displays fancy error messages.
As usual, please see individual commits for …

Improve extended Exordium help

---

.gitignore
modules/init-elisp.el
modules/init-iwyu.el
modules/init-lib.el
modules/init-util.el
modules/init-util.t.el
modules/init-window-manager.el

A few improvements, that I think are small enough to avoid creating a separate PR for each.
- don't ask whether to kill empty scratch buffers
- use a proper key substitution in IWYU mode
- use exordium-page-break-lines consistently
- add multisession to gitignore
- don't bind M-o in diff-mode to avoid hijacking ace-window
- use built-in function for duplicate line or region
Please see each commit for a separate changeset

Assorted improvements

---

README.md
modules/init-helm-projectile.el
modules/init-helm.el

This ensures consistency when switching to buffers using different methods, for
example `swich-to-buffer`, <kbd>C-x b</kbd>, `swich-to-buffer-other-window`,
<kbd>C-x 4 b</kbd>, or `projectile-switch-to-buffer`, <kbd>C-c p b</kbd>.
Using the opportunity to add a few minor fixes, and a couple of new keybindings.
As usual, please see individual commits for details.

Add affixations to buffer switching functions when exordium-help-extensions

---

modules/init-helm-projectile.el
modules/init-helm.el

This fixes commands `switch-to-buffer-other-window` and
`switch-to-buffer-other-frame` such that they don't switch buffer in current
window. A bug introduced in #240.
Also ensure that the same `helm`s are used when switching project with
`helm-projectile`, and add affixations to switching project buffers to other
window and other frame.
As usual, please see individual commits for details.

Ensure consistency when switching buffers with helm

---

themes/color-theme-tomorrow.el

This PR makes a simple change to the look of org-mode level 1 headline, removing the overline. It is visually distracting for long org documents, and it is also different from all the other themes in Exordium.
Off-topic, but I discovered how to create custom startup options for org-mode. One can re-add this overline by adding `#+startup: showline` in an org file, provided that you have the following code in one of your Exordium taps:
```elisp
;;; Custom startup options for org-mode
(defvar my-org-mode-showlines nil)
(add-to-list 'org-startup-options '("showlines" my-org-mode-showlines t))
(add-hook 'org-mode-hook
(lambda ()
(when my-org-mode-showlines
(face-remap-add-relative 'org-level-1
(with-tomorrow-colors 'night `(:overline ,green))))))
```

Disable org-level-1 overline in Tommorrow theme

---

.github/workflows/tests.yml

Workflow name is reflected in rendered workflow status web page title. When
there are many open tabs in a browser, their names are truncated. When using
specific words in the beginning of a name it is easier to fish out required
tab.

ci: Add Emacs-30.1 to test matrix and rename workflow

---

modules/init-helm.el
modules/init-prefs.el
modules/init-window-manager.el

Port functionality of splitting by the longest direction from Emacs 30 and
adjust `helm` to use the same functions to perform splits.
@philippe-grenet I hope this is a reasonable solution to [the issue](https://github.com/emacs-exordium/exordium/pull/227#discussion_r1874938162)  that has been flagged in #227.

feat: Customiseable window splitting direction

---

modules/init-bde-style.el

In Emacs 30.2 the syntax entries has changed:
- for the opening brace after function argument list to
`brace-entry-open` (form `inline-open` in Emacs 29.4 and Emacs 30.1).
- for the opening parenthesis for argument list to `brace-list-intro` (from
`topmost-intro` in Emacs 29.4 and Emacs 30.1).
This fixes the following failure (as observed in
https://github.com/emacs-exordium/exordium/actions/runs/14177899574/job/39717058426):
```
4 unexpected results:
FAILED  test-exordium-bde-bounds-of-arglist-at-point-commas-in-assign-1  ((should (equal (with-test-case-return tst (exordium-bde-bounds-of-arglist-at-point)) (cons 24 222))) :form (equal nil (24 . 222)) :value nil :explanation (different-types nil (24 . 222)))
FAILED  test-exordium-bde-bounds-of-arglist-at-point-commas-in-assign-2  ((should …
```

fix: Update searching for function arguments parenthesis

---

README.md
modules/init-forge.el
modules/init-git.el
modules/init-lib.el
modules/init-look-and-feel.el
modules/init-osx.el
modules/init-window-manager.el

Below are a few small fixes I discovered while using Emacs from master branch
(30.1.50), if you're on macOS and fan of Mitsuharu's Emacs-mac you can check
out https://github.com/pkryger/homebrew-emacsmacport-exp `</shameless-plug>`).
Emacs-snapshot has started to complain about that with:
```
init-git.el: Warning: the function ‘transient--set-layout’ might not be defined at runtime.
```
Recent change has introduced a bug where a man page cannot be displayed. This
is annoying in places like transient prefixes, where one can invoke a manual
with just `C-h C-h`.
Show `exordium-smerge-dispatch` if necessary after visiting a file with one of
the `difftastic-diff-visit-file` or `difftastic-diff-visit-worktree-file`
(bound respectively to `RET` and `C-RET` in `difftastic-mode`).
This is similar …

feat: Fixes for Emacs 30
