extensions/profile-dotemacs.el, init.el, modules/init-clojure.el, modules/init-themes.el, modules/init-util.el, modules/init-yasnippet.el, vendor/clojure.el
Use user-emacs-directory and locate-user-emacs-file to find things
This means init can be tested with
emacs -Q --eval "(progn
(setq user-emacs-directory \"~/src/pg-dot-emacs/dot.emacs/\")
(load-file \"~/src/pg-dot-emacs/dot.emacs/init.el\"))"
=> Look up paths based on user-dir variable

init.el
Custom variable for auto update of additional packages beyond the base ones for Exordium.
=> Add package variable

init.el
Load subdirectories under local, so that local can have git repos stored there. e.g: https://github.com/steve-downey/smd.emacs.git
=> Add local subdirs

modules/init-git.el
Allow additional bindings of the git subcommands
(e.g. C-x g on the global map)
=> Define keymap for git commands

modules/init-prefs.el, modules/init-util.el
Added a small update that saves a few keystrokes when updating your own taps
=> Make taps to update with update-config

init.el
Variables for package repo urls and a list of pinned packages.
=> Allow pinning packages to stable melpa

themes/color-theme-solarized.el
Let foreground be a light one  as it goes into pretty dark background.
=> Update solarized-dark powerline vc colour

themes/color-theme-solarized.el
Use definitions from https://github.com/bbatsov/solarized-emacs/
=> Make helm colours for solarized theme less loud

themes/color-theme-solarized.el
Again,  based on https://github.com/bbatsov/solarized-emacs/blob/master/solarized.el
=> Make diff colours for solarized theme less loud

modules/init-git.el
Add git-grep to to C-c g keymap
=>  Add git grep to the git keymap

modules/init-look-and-feel.el
Make exordium set font interactive. Make default choice and size
available as variables.
=> Interactive set-font

init.el, modules/init-progress-bar.el
Also fix the count on the progress bar steps.
=> Add progress bar step

themes/color-theme-zenburn.el
The default yellow was too tacky to my taste.
=> Update zenburn color theme for company mode

modules/init-cpp.el, themes/color-theme-zenburn.el
A couple of adjustments for zenburn them so company
doesn't come up with it's (too) lively colors.
=> Fine tune zenburn for company mode

modules/init-rtags.el
OK OK recenter then...looks like this does it.
=> rtags: fix recenter on find-symbol-at-point

README.md, init.el, modules/init-iwyu.el, modules/init-prefs.el
This is my first take on it. The support is pretty rudimentary
but is seems to work. Will work on any other features upon request
or when I find a need to have them. One, that already made my list
is some minor mode to color the diagnostic buffer.
=> Add include-what-you-use

modules/init-iwyu.el
It detects and concatenates `\"args like this\"` before
passing them to a `include-what-you-use` process.
=> Fixup for IWYU args parsing

modules/init-iwyu.el
A little bit of colors is always good. It bases on `compilation`
mode so errors are automagically highlighted.
=> Add IWYU mode

modules/init-bde-style.el
- rename `bde-aligh-right` to `bde-align-right`
- update comment in `bde-guess-class-name`
- remove debug from `bde-guess-class-name`
=> Fix function name, comment and remove debug

README.md
=> fix magit link

README.md, modules/init-look-and-feel.el
I've been finding this really useful when using Eclipse.
=> Add move region up/down

modules/init-rtags.el
We were using an outdated copy of rtags-find-symbol-at-point. Get rid of this. Re-centering can be done - better - via a hook. This also fixes jumping to a symbol in another window. Which is now supported in stock rtags.
=> rtags: get rid of exordium-rtags-find-symbol-at-point

README.md, modules/init-git.el
When helm everywhere is enabled.
=> Use helm for git grep

modules/init-git.el
This commit addresses only `init-git.el`.
=> Make functions bound to keys commands for magit

themes/color-theme-tomorrow.el
Improves a few of Tomorrow's colors for Helm and Org mode
=> Improve a few of tomorrow's theme colors

modules/init-org.el
Support shift select outside org contexts where it does something else.
----
#
=> Set org-support-shift-select

modules/init-helm-projectile.el
This was a copy-pasta from my config, that I later scattered over exordium config in #179. But never got back to delete the temporary code.
=> Add extra helm-projectile actions only once

modules/init-forge.el
I wanted to `exordium-forge-cleanup-known-repositories`, but it didn't work for some reason. It turns out that the `forge-find-repository` needs a forge host to be registered in a `forge-alist`. Long story short, I've learned something new - `async-inject-variables`. This also simplifies the code as the `to-delete` list can be injected as well 😎.
When I'd done it for a first time, I cleaned up repositories synchronously. Only later has rewritten it in `async` terms, but the latter was tested only on `github.com` repository, which - surprise, surprise - is on a default `forge-alist`.
=> Use async-inject-variables when cleaning repositories

modules/init-git.el
When entering a fullscreen mode for `magit` commands a current window configuration is saved into a register. When the `magit` command is finished the configuration is restored from the register.
Instead of using a single register a new name is generated for each tab (when in `tab-bar-mode`) and each frame. That way, when there are multiple concurrent `magit` sessions in an Emacs instance each of them is holding to its own window configuration. With that, when a `magit` session is finished it restores a window configuration that had been in a given frame/tab.
I'm a little uncertain about register names. For one these are fairly long. Personally I'm not using `jump-to-register` a lot (almost none), but if someone does - this may become nuisance.
The second thing is a unique name for …
=> Support multiple frames and tabs for magit fullscreen

.ci/compilation.sh, .ci/first-start.sh, .ci/unit-test-cl.sh, .github/workflows/tests.yml, .gitignore, README.md, init.el, modules/init-org.el, modules/init-themes.el, modules/init-util.el
I hope I caught all workarounds.
Please note that my taps in CI don't work (`tree-sitter` seems to be incompatible with `silex/emacs`), but I neither have figured out how to disable it during CI nor I have found a real fix to the problem.
=> Bump minimum supported version to emacs-27.1

README.md, init.el, modules/init-bde-style.t.el, modules/init-company.el, modules/init-docker.el, modules/init-lsp.el, modules/init-prefs.el
LSP-mode and docker support for localdev on C++ projects.
=> Lsp local dev

init.el
I noticed this typo while looking through the code
=> Fix typo in init.el

.github/workflows/tests.yml, .gitignore, init.el, modules/init-autocomplete.el, modules/init-company.el, modules/init-cpp.el, modules/init-forge.el, modules/init-git.el, modules/init-helm-projectile.el, modules/init-helm.el, modules/init-help.el, modules/init-iwyu.el, modules/init-osx.el, modules/init-rtags-helm.el, modules/init-ruby.el
I decided to submit this as a single PR, as majority of these commits are limited in scope to a few lines.
These are various fixes (like no `-i` for `zsh`, or late `desktop` load) as well as some improvements. In the past I had quite a good track record with CI stability on this branch, so I guess some of them are fixes indeed (the single packages thingy perhaps?).
=> Assorted fixes and improvements

modules/init-git.el
Debugged this with PRZEMEK KRYGER at $job.
=> Cannot remove single quotes in this context, at least under emacs 27.2

modules/init-highlight.el
Was trying to sort out a theme problem with hl-line, this turned out to be unrelated, but seems reasonable.
=> Convert hl-line to use-package form

modules/init-desktop.el, modules/init-look-and-feel.el, modules/init-themes.el
Enable better support for daemon mode, with delayed loading of themes, fonts, and desktop
=> Better daemon

init.el
Seq was updated to 24 in emacs-29.2
=> Seq updated

init.el, modules/init-cpp.el, modules/init-org.el, modules/init-prefs.el
HIghlight dead code in in the c-ts-mode
Clangd binary names update
Org mode from elpa
Elpa compilation dir not hardcoded to ~/.emacs.d/
=> Misc small fixes

modules/init-look-and-feel.el
Use `child-frame` (as a value of `show-paren-context-when-offscreen`, since the
`overlay` is not always visible, (see
https://github.com/jdtsmith/ultra-scroll/issues/20 for more details).
Also add a couple extensions, like making the child frame border that displays
the context in the same colour as the matching paren as well as hightlight the
matchin paren in the context (assume: single character).
=> feat: Show context around the opening paren if it is offscreen

README.md
Make sure local modules can be found as local directory is not in load-path.
=> Update readme about local modules.
